version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Restore
          command: dotnet restore
          working_directory: BriskDotNet
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: BriskDotNet
      - run:
          name: Pack
          command: dotnet pack BriskDotNet/BriskDotNet.csproj --output nupkgs -c Release
      - run:
          name: Push to Nuget
          command: dotnet nuget push $(find nupkgs -mindepth 1 -print -quit) -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
